global:
  scrape_interval: 15s # Raspar as métricas a cada 15 segundos

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'ubuntu'
    static_configs:
       - targets: ['172.22.0.2:9100']

  - job_name: 'debian'
    static_configs:
      - targets: ['172.22.0.5:9100']