global:
  scrape_interval: 15s # Raspar as métricas a cada 15 segundos

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'ubuntu'
    static_configs:

      - targets: ['172.28.0.20:9100']
      
  - job_name: 'debian'
    static_configs:
      - targets: ['172.28.0.10:9100']

  # Adicionar OpenTelemetry Collector como fonte de métricas
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 10s

  # Jaeger metrics (se disponível)
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    scrape_interval: 15s